(function () {
  window.PlaybookCamposData = {
    version: "2026-04-14-phase1",
    enums: {
      entities: ["ticket", "contact_customer"],
      classifications: ["mandatory", "recommended", "automatic", "conditional"],
      stages: [
        "opening",
        "in_progress",
        "waiting_customer",
        "waiting_parts",
        "waiting_third_party",
        "resolution_closing",
        "system"
      ],
      owners: ["customer", "agent", "system", "coordinator"],
      impacts: ["data_quality", "flow", "priority", "sla", "kpi", "audit"],
      sources: ["customer", "zoho_desk", "agent", "system"],
      inputTypes: ["text", "list", "yes_no", "date", "automatic"]
    },
    fields: [
      {
        id: "ticket-requester-name",
        entity: "ticket",
        field: "ticket_requester_name",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["data_quality", "flow"],
        description: "Identificacao principal de quem abriu o chamado.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-email",
        entity: "ticket",
        field: "ticket_email",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["flow", "sla"],
        description: "Canal formal para retorno.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-phone",
        entity: "ticket",
        field: "ticket_phone",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["flow", "sla"],
        description: "Canal imediato para contato.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-requester-profile",
        entity: "ticket",
        field: "ticket_requester_profile",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["priority", "flow"],
        description: "Perfil de quem solicita o atendimento.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "list",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-service-type",
        entity: "ticket",
        field: "ticket_service_type",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["priority", "flow", "sla"],
        description: "Define natureza da demanda.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "list",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-category",
        entity: "ticket",
        field: "ticket_category",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["priority", "kpi"],
        description: "Categoria principal do ticket.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "list",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-product",
        entity: "ticket",
        field: "ticket_product",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["priority", "kpi"],
        description: "Produto associado ao chamado.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "list",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-product-brand",
        entity: "ticket",
        field: "ticket_product_brand",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["data_quality", "kpi"],
        description: "Marca do produto atendido.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "list",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-equipment-serial-number",
        entity: "ticket",
        field: "ticket_equipment_serial_number",
        classification: "mandatory",
        condition: "serial_exception",
        stage: "opening",
        owner: "customer",
        impact: ["data_quality", "audit"],
        description: "Identificador tecnico do equipamento.",
        requiredRule: "mandatory_serial_exception",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-subject",
        entity: "ticket",
        field: "ticket_subject",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["flow"],
        description: "Resumo curto do problema.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-description",
        entity: "ticket",
        field: "ticket_description",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["flow", "audit"],
        description: "Detalhamento do chamado.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-state",
        entity: "ticket",
        field: "ticket_state",
        classification: "conditional",
        condition: "country_brazil",
        stage: "opening",
        owner: "customer",
        impact: ["flow", "audit"],
        description: "Dado regional para Brasil.",
        requiredRule: "conditional_brazil_state",
        source: "customer",
        inputType: "list",
        globalRule: false,
        regionalRule: "br_only_state"
      },
      {
        id: "ticket-province",
        entity: "ticket",
        field: "ticket_province",
        classification: "conditional",
        condition: "country_argentina",
        stage: "opening",
        owner: "customer",
        impact: ["flow", "audit"],
        description: "Dado regional para Argentina.",
        requiredRule: "conditional_argentina_province",
        source: "customer",
        inputType: "list",
        globalRule: false,
        regionalRule: "ar_only_province"
      },
      {
        id: "ticket-assistance-distributor-name",
        entity: "ticket",
        field: "ticket_assistance_distributor_name",
        classification: "conditional",
        condition: "requester_assistance_distributor",
        stage: "opening",
        owner: "customer",
        impact: ["flow", "data_quality"],
        description: "Identificacao de parceiro quando aplicavel.",
        requiredRule: "conditional_assistance_distributor",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-country",
        entity: "ticket",
        field: "ticket_country",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["data_quality"],
        description: "Contexto geografico complementar.",
        requiredRule: "country_not_mandatory",
        source: "customer",
        inputType: "list",
        globalRule: false,
        regionalRule: null
      },
      {
        id: "ticket-id",
        entity: "ticket",
        field: "ticket_id",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["audit", "flow"],
        description: "Identificador unico do ticket.",
        requiredRule: "automatic_system",
        source: "zoho_desk",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-opening-date",
        entity: "ticket",
        field: "ticket_opening_date",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["sla", "kpi", "audit"],
        description: "Data/hora de criacao do ticket.",
        requiredRule: "automatic_system",
        source: "zoho_desk",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-channel",
        entity: "ticket",
        field: "ticket_channel",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["flow", "kpi"],
        description: "Origem do chamado.",
        requiredRule: "automatic_system",
        source: "zoho_desk",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-owner",
        entity: "ticket",
        field: "ticket_owner",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "coordinator",
        impact: ["flow", "audit"],
        description: "Responsavel atual no sistema.",
        requiredRule: "automatic_system",
        source: "zoho_desk",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-status",
        entity: "ticket",
        field: "ticket_status",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["flow", "sla", "kpi"],
        description: "Status corrente do ticket.",
        requiredRule: "automatic_system",
        source: "zoho_desk",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-priority",
        entity: "ticket",
        field: "ticket_priority",
        classification: "mandatory",
        condition: "priority_calculated_matrix",
        stage: "system",
        owner: "system",
        impact: ["priority", "flow", "sla", "kpi"],
        description: "Prioridade oficial para ordenacao da fila.",
        requiredRule: "mandatory_priority_matrix",
        source: "zoho_desk",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-sla-first-response",
        entity: "ticket",
        field: "ticket_sla_first_response",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["sla", "kpi"],
        description: "Meta de primeira resposta.",
        requiredRule: "automatic_system",
        source: "zoho_desk",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-sla-resolution",
        entity: "ticket",
        field: "ticket_sla_resolution",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["sla", "kpi"],
        description: "Meta de resolucao.",
        requiredRule: "automatic_system",
        source: "zoho_desk",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-first-response-date",
        entity: "ticket",
        field: "ticket_first_response_date",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["sla", "kpi", "audit"],
        description: "Data/hora da primeira resposta.",
        requiredRule: "automatic_system",
        source: "system",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-closing-date",
        entity: "ticket",
        field: "ticket_closing_date",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["kpi", "audit"],
        description: "Data/hora de fechamento.",
        requiredRule: "automatic_system",
        source: "system",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-time-to-first-response",
        entity: "ticket",
        field: "ticket_time_to_first_response",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["sla", "kpi"],
        description: "Tempo calculado ate primeira resposta.",
        requiredRule: "automatic_system",
        source: "system",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-total-time-to-close",
        entity: "ticket",
        field: "ticket_total_time_to_close",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["sla", "kpi"],
        description: "Tempo total calculado ate fechamento.",
        requiredRule: "automatic_system",
        source: "system",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-sla-compliance-indicator",
        entity: "ticket",
        field: "ticket_sla_compliance_indicator",
        classification: "automatic",
        condition: null,
        stage: "system",
        owner: "system",
        impact: ["sla", "kpi", "audit"],
        description: "Indicador de cumprimento de SLA.",
        requiredRule: "automatic_system",
        source: "system",
        inputType: "automatic",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-zero-hour-out-of-box",
        entity: "ticket",
        field: "ticket_zero_hour_out_of_box",
        classification: "recommended",
        condition: null,
        stage: "in_progress",
        owner: "agent",
        impact: ["priority", "sla", "kpi"],
        description: "Sinaliza caso critico de operacao imediata.",
        requiredRule: "recommended_zero_hour",
        source: "agent",
        inputType: "yes_no",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-needs-part",
        entity: "ticket",
        field: "ticket_needs_part",
        classification: "recommended",
        condition: null,
        stage: "waiting_parts",
        owner: "agent",
        impact: ["flow", "priority"],
        description: "Indica dependencia de peca.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "yes_no",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-partner-distributor",
        entity: "ticket",
        field: "ticket_partner_distributor",
        classification: "recommended",
        condition: "partner_not_captured",
        stage: "in_progress",
        owner: "agent",
        impact: ["data_quality", "flow"],
        description: "Complemento de parceiro/distribuidor.",
        requiredRule: "recommended_partner_if_missing",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-rac-sent",
        entity: "ticket",
        field: "ticket_rac_sent",
        classification: "recommended",
        condition: null,
        stage: "waiting_third_party",
        owner: "agent",
        impact: ["audit", "flow"],
        description: "Controle de envio de RAC.",
        requiredRule: "recommended_rac_yes_no",
        source: "agent",
        inputType: "yes_no",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-technical-assistance-type",
        entity: "ticket",
        field: "ticket_technical_assistance_type",
        classification: "recommended",
        condition: null,
        stage: "waiting_third_party",
        owner: "agent",
        impact: ["flow", "data_quality"],
        description: "Tipo de assistencia tecnica utilizada.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "list",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-resolution-summary",
        entity: "ticket",
        field: "ticket_resolution_summary",
        classification: "mandatory",
        condition: null,
        stage: "resolution_closing",
        owner: "agent",
        impact: ["audit", "data_quality"],
        description: "Resumo final da resolucao aplicada.",
        requiredRule: "mandatory_closing_summary",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-closing-reason",
        entity: "ticket",
        field: "ticket_closing_reason",
        classification: "recommended",
        condition: null,
        stage: "resolution_closing",
        owner: "agent",
        impact: ["kpi", "audit"],
        description: "Motivo operacional do fechamento.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "list",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-on-site-or-remote-solution",
        entity: "ticket",
        field: "ticket_on_site_or_remote_solution",
        classification: "recommended",
        condition: null,
        stage: "resolution_closing",
        owner: "agent",
        impact: ["kpi"],
        description: "Forma da solucao aplicada.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "list",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-used-part",
        entity: "ticket",
        field: "ticket_used_part",
        classification: "recommended",
        condition: null,
        stage: "resolution_closing",
        owner: "agent",
        impact: ["data_quality", "audit"],
        description: "Peca efetivamente utilizada.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "ticket-final-parts-quantity",
        entity: "ticket",
        field: "ticket_final_parts_quantity",
        classification: "recommended",
        condition: null,
        stage: "resolution_closing",
        owner: "agent",
        impact: ["data_quality", "kpi"],
        description: "Quantidade final de pecas usadas.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-first-name",
        entity: "contact_customer",
        field: "contact_first_name",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["data_quality", "flow"],
        description: "Nome principal do contato.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-last-name",
        entity: "contact_customer",
        field: "contact_last_name",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["data_quality", "flow"],
        description: "Sobrenome principal do contato.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-account-name",
        entity: "contact_customer",
        field: "contact_account_name",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["data_quality", "flow"],
        description: "Conta vinculada ao contato.",
        requiredRule: "mandatory_opening",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-email",
        entity: "contact_customer",
        field: "contact_email",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["flow", "sla"],
        description: "Canal formal de contato do cadastro.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-phone-mobile",
        entity: "contact_customer",
        field: "contact_phone_mobile",
        classification: "mandatory",
        condition: null,
        stage: "opening",
        owner: "customer",
        impact: ["flow", "sla"],
        description: "Telefone principal do contato.",
        requiredRule: "mandatory_opening",
        source: "customer",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-legal-name",
        entity: "contact_customer",
        field: "contact_legal_name",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["data_quality", "audit"],
        description: "Razao social do cadastro corporativo.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-trade-name",
        entity: "contact_customer",
        field: "contact_trade_name",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["data_quality"],
        description: "Nome fantasia da conta.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-language",
        entity: "contact_customer",
        field: "contact_language",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["flow"],
        description: "Idioma preferencial de comunicacao.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "list",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-address",
        entity: "contact_customer",
        field: "contact_address",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["data_quality", "flow"],
        description: "Endereco principal do contato.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-scanner-model",
        entity: "contact_customer",
        field: "contact_scanner_model",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["data_quality", "kpi"],
        description: "Modelo do scanner.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-installation-date",
        entity: "contact_customer",
        field: "contact_installation_date",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["kpi", "audit"],
        description: "Data de instalacao.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "date",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-dealer",
        entity: "contact_customer",
        field: "contact_dealer",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["flow", "audit"],
        description: "Distribuidor do equipamento.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-scanner-serial-number",
        entity: "contact_customer",
        field: "contact_scanner_serial_number",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["data_quality", "audit"],
        description: "Serial do scanner cadastrado.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-pc-model",
        entity: "contact_customer",
        field: "contact_pc_model",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["data_quality"],
        description: "Modelo do PC vinculado.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-pc-serial-number",
        entity: "contact_customer",
        field: "contact_pc_serial_number",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["data_quality", "audit"],
        description: "Serial do PC vinculado.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-parts-warranty",
        entity: "contact_customer",
        field: "contact_parts_warranty",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["flow", "kpi"],
        description: "Status da garantia de pecas.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-labor-warranty",
        entity: "contact_customer",
        field: "contact_labor_warranty",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["flow", "kpi"],
        description: "Status da garantia de mao de obra.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: true,
        regionalRule: null
      },
      {
        id: "contact-fda-2579-form-number",
        entity: "contact_customer",
        field: "contact_fda_2579_form_number",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["audit"],
        description: "Numero do formulario regulatorio.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "text",
        globalRule: false,
        regionalRule: null
      },
      {
        id: "contact-fda-2579-form-date",
        entity: "contact_customer",
        field: "contact_fda_2579_form_date",
        classification: "recommended",
        condition: null,
        stage: "opening",
        owner: "agent",
        impact: ["audit"],
        description: "Data do formulario regulatorio.",
        requiredRule: "recommended_general",
        source: "agent",
        inputType: "date",
        globalRule: false,
        regionalRule: null
      }
    ]
  };
})();
